### ISSUE TITLE
No results returned for some queries

### ISSUE THREAD

**Issue by NeonDaniel** [HelloChatterbox/youtube_searcher#4]
I was able to get results be iterating over the items in "primary_contents_list" rather than taking just index [0], which in these examples contained only ad links. This did not appear to cause issues with other searches, nor do I see any conditions where this would break things.

Example searches with no results:
"repair a faucet tutorial"
"algebra tutorial"
"rewire a lamp tutorial"

**Comment by JarbasAl** [comment]
fixed in https://github.com/HelloChatterbox/youtube_searcher/commit/4981ae38f7b28e0d467ca098d882fe3c32cae06e, thank you once again
